---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Upgrade all packages on servers
    apt: upgrade=dist force_apt_get=yes

  - name: Install Apache2
    apt:
      name: apache2
      state: present

  - name: Ensure that apache2 is started
    service: name=apache2 state=started

- hosts: all
  become: true
  remote_user: ubuntu
  roles:
    - geerlingguy.docker

- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Make sure Docker service is running
    systemd:
      state: started
      name: docker
