apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: "{{ .Values.name }}" 
  namespace: flaskapp
spec: 
  selector: 
    matchLabels: 
      app: "{{ .Values.name }}" 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: "{{ .Values.name }}"
    spec: 
      containers: 
      - name: "{{ .Values.name }}" 
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        ports: 
        - containerPort: 5000