# will create only 1 node cluster.
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: us-east-1
  version: "1.21"

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1