apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: devops
  region: us-west-1
  version: "1.21"
managedNodeGroups:
- name: primary-1-21
  instanceType: t2.small
  minSize: 3
  maxSize: 6
  # spot: true
  