apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: weather-deployment 
spec: 
  selector: 
    matchLabels: 
      app: weather 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: weather
    spec: 
      containers: 
      - name: weather 
        image: jack17529/weather
        ports: 
        - containerPort: 5000

